### ISSUE TITLE
Top nav bar too tall

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#1]
Should be fixed height of 66px, and should not change sizes when scrolling.

<img width="481" alt="screen_shot_2017-11-14_at_9_28_24_am" src="https://user-images.githubusercontent.com/30864/32788495-f1f29e74-c91e-11e7-9a89-9d0384b5b84f.png">

**Comment by sassinator** [comment]
done on staging

**Comment by dcgrigsby** [comment]
The header still changes size when scrolling:

![nov-22-2017 12-04-53](https://user-images.githubusercontent.com/30864/33142843-6c3edfa8-cf7d-11e7-9117-96b14e76a71c.gif)

**Comment by sassinator** [comment]
ah yes, sorry, missed the size change on scroll. thx.

**Comment by sassinator** [comment]
@dcgrigsby removed size change on scroll.
