### ISSUE TITLE
Front Page - Our Story

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#11]
Image should not zoom (same issue as Hero)

H1 font weight 300

p is narrower by 100px than original template; font size not the same

<img width="97" alt="screen shot 2017-11-14 at 10 47 52 am" src="https://user-images.githubusercontent.com/30864/32792597-584fb288-c929-11e7-89db-23f0820ed25f.png">

**Comment by sassinator** [comment]
@dcgrigsby very close now to original now - no zoom, fonts match. please take a look on staging.
