### ISSUE TITLE
Front page - Explore 

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#12]
h3 32px 100weight

Add 80x padding top to H2

<img width="636" alt="wildflower_schools" src="https://user-images.githubusercontent.com/30864/32793046-788a8022-c92a-11e7-92b3-712a5b6fa60a.png">

**Comment by sassinator** [comment]
@dcgrigsby i'd like to discuss this one.

**Comment by dcgrigsby** [comment]
decided not to fix
