### ISSUE TITLE
Front page - social media icons

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#13]
Should be smaller, spaced tighter, equal height (50px, for alignment), with 50px between them

<img width="408" alt="screen_shot_2017-11-14_at_11_01_33_am" src="https://user-images.githubusercontent.com/30864/32793412-7857b0b0-c92b-11e7-8522-19a6e4e0a659.png">

**Comment by sassinator** [comment]
fixed on staging.
