### ISSUE TITLE
Default text font/weight

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#19]
The (what I assume is) default text is a bit heavier and/or darker.  When I use the inspector, they appear the same, but you can see they're visibly different:

<img width="384" alt="untitled" src="https://user-images.githubusercontent.com/30864/32794688-21eb3086-c92f-11e7-953b-d1b6b6df9ba7.png">

**Comment by dcgrigsby** [comment]
I used the inspector to change the new to be font weight 300; that produced the desired effect, so use that font weight

**Comment by sassinator** [comment]
Let's use body copy on Our Principles page as reference.

**Comment by sassinator** [comment]
@dcgrigsby should be the same now. there were some aliasing settings that were affecting fonts.
