### ISSUE TITLE
Flash of Unstyled Text (FOUT)

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#2]
When the page first renders the webfonts aren't yet loaded, so the text flashes.  See:

https://helpx.adobe.com/typekit/using/font-events.html

Please duplicate the old theme's method of dealing with this, namely adding CSS to hide the text until the webfonts load.  Here is the CSS:

.wf-loading {
  display: none;
}

**Comment by sassinator** [comment]
@dcgrigsby please take a look and see if this is now working as expected.

**Comment by dcgrigsby** [comment]
appears to have been fixed by @sassinator
