### ISSUE TITLE
Our Principles page missing top section

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#20]
The Our Principles page is missing the top section (pic with Sep and his kid, plus text)

<img width="1244" alt="screen shot 2017-11-14 at 11 44 33 am" src="https://user-images.githubusercontent.com/30864/32795519-89c89084-c931-11e7-898d-ac1d81d3e968.png">

Note, like one other issue, this did not show up in the staging env but was present in the live site.

**Comment by sassinator** [comment]
@dcgrigsby should be good now and working with responsive.
