### ISSUE TITLE
Our Principles - responsive design

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#22]
Text overflows 

<img width="689" alt="screen_shot_2017-11-14_at_12_08_51_pm" src="https://user-images.githubusercontent.com/30864/32796604-db2b7e66-c934-11e7-9e4c-e11bc31f9b4b.png">

**Comment by dcgrigsby** [comment]
The height is fixed and I used "background-size: cover;" to make the image behave as desired

![nov-14-2017 12-16-12](https://user-images.githubusercontent.com/30864/32796874-a3fc10d0-c935-11e7-8cb5-caec6b28cef0.gif)

.

**Comment by sassinator** [comment]
We may have to take a slightly different approach to work with the theme. Getting closer, still need some tweaks:

![image](https://user-images.githubusercontent.com/6728316/32983326-6cd0bbd0-cc58-11e7-9d92-70fe5e03ebfe.png)

**Comment by sassinator** [comment]
@dcgrigsby i think this is very close to the original now.

**Comment by dcgrigsby** [comment]
Close enough.  Thanks.
