### ISSUE TITLE
Front-page - Facebook links to MN WF, should be National FB Page

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#24]
Correct link https://www.facebook.com/wildflowerschools/

**Comment by sassinator** [comment]
done on staging.

**Comment by dcgrigsby** [comment]
@sassinator  - thanks.  I just saw that the live site used the MN FB, so this was our fault.  Sorry about that.  Please have the social media links open in new windows and I'll close this.

**Comment by sassinator** [comment]
no problem.

**Comment by sassinator** [comment]
@dcgrigsby opens in new window now.
