### ISSUE TITLE
Our networks spacing and alignment

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#25]
<img width="673" alt="our_network_ _wildflower_schools" src="https://user-images.githubusercontent.com/30864/33143201-c27093fc-cf7e-11e7-9241-d2c5b26da245.png">

(a) and (b) should be same offset from edge

(c) should be like

<img width="613" alt="screen shot 2017-11-22 at 12 13 28 pm" src="https://user-images.githubusercontent.com/30864/33143169-a0642526-cf7e-11e7-997b-993f1d497061.png">

**Comment by sassinator** [comment]
@dcgrigsby I'd like to discuss this one. Thanks.

**Comment by sassinator** [comment]
it's just a bit of work due to caution and testing around the syndication.
