### ISSUE TITLE
Our story image zoomed

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#26]
![nov-27-2017 09-36-03](https://user-images.githubusercontent.com/30864/33274720-84156dc2-d356-11e7-9f13-60fb879b1872.gif)

**Comment by sassinator** [comment]
@dcgrigsby this one is interesting. the image zoomed when we turned off the row to row scrolling effect and turned on a parallax effect as in the original. however that causes a zoom that i'm not sure we can easily control. in fact the original is zooming the image as well just to a lessor amount. We could easily turn off the parallax effect and control the zoom of the image. thoughts?

**Comment by dcgrigsby** [comment]
Does the current site have a parallax effect?  If not, and turning it off will allow you to duplicate the current look, then do that.

**Comment by sassinator** [comment]
@dcgrigsby yes, it does. it's the effect where the image background scrolls much slower than the foreground text.

**Comment by dcgrigsby** [comment]
decided not to fix
