### ISSUE TITLE
Get Involved Page and Form not rendering properly

### ISSUE THREAD

**Issue by btalberg** [WildflowerSchools/website-qa#27]
Compare the [staging site's Get Involved page](https://wildflowerschools-org.wfschools.staging.wpengine.com/get-involved/) to [production's Get Involved page](https://wildflowerschools.org/get-involved/).

Things I notice (let me know if you'd like screen shots for any of the below):

- Content width (`entry-content`) now fills full page, should have `max-width = 750px`
- Page content `h3` headers have no margin-bottom, should have `margin-bottom = 24px`
- Form headers/labels should use bold font styling (`font-weight = 700`)
- Form headers/labels should use larger font (`font-size = 20px`)
- Form selections should use bold font styling (`font-weight = 700`)
- Form options should use black font color
- Form text-areas should more clearly demarcate the location of the text entry region, the current white background blends into the page and it's not easy to see where the user should click or where the user should begin typing
- Form text-areas header + description fields overlap and should not use on-selected position swapping behavior (click in the Message text-area on staging and you'll see what I mean)
- Form submit button should use bold font (`font-weight = 700`)
- Form submit button should use all caps

**Comment by sassinator** [comment]
noted. yes the new theme is affecting the styling.

**Comment by dcgrigsby** [comment]
fixed by @btalberg
