### ISSUE TITLE
Top nav bar logo size

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#4]
Should be 67x33

<img width="179" alt="screen shot 2017-11-14 at 9 45 55 am" src="https://user-images.githubusercontent.com/30864/32789153-a95d47d4-c920-11e7-9159-94cbbde125a1.png">

**Comment by sassinator** [comment]
Done on stage.

**Comment by dcgrigsby** [comment]
It's still too narrow.  For comparison:

<img width="1280" alt="screen shot 2017-11-22 at 12 09 09 pm" src="https://user-images.githubusercontent.com/30864/33142992-00a48058-cf7e-11e7-9e2b-f7ad6775d7d7.png">

**Comment by sassinator** [comment]
This one is very very close. The theme is doing something to it to make it squish a tiny amount. Would like to recommend calling it complete or include in final list once we are clear on tasks to move forward with.
