### ISSUE TITLE
Front page - fonts - Hero - fonts, spacing for text and buttons

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#7]
H1 should be 72px, should have 24px bottom margin
H2 should be 38px, should have 32px bottom margin

Apply Now button should 200x50px with font weight 100.  

Note the padding on the left and the right.  Your HTML is structured different, so setting the left and right padding to 26x won't produce the correct result.

<img width="851" alt="screen_shot_2017-11-14_at_10_11_40_am" src="https://user-images.githubusercontent.com/30864/32790610-84cc10b8-c924-11e7-8b97-df894836e250.png">

Note the change in font weight and background on mouse-over:

![nov-14-2017 10-17-30](https://user-images.githubusercontent.com/30864/32790856-2907f4f8-c925-11e7-8840-66dcd82bde67.gif)

Get Involved button should, likewise, be sized 200x50.  It should be 600 weight.

Its mouse-over:

![nov-14-2017 10-21-06](https://user-images.githubusercontent.com/30864/32791008-92b7888c-c925-11e7-906a-34ae34b2fa7e.gif)

**Comment by sassinator** [comment]
getting there. need to fix responsive still.

**Comment by sassinator** [comment]
@dcgrigsby I think we're good now on this one.
