### ISSUE TITLE
Front-page - learn more buttons

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#8]
Same dimensions, font weight and mouse-over as Get Involved button

**Comment by sassinator** [comment]
would like to leave dimension determined by text length. change font weight and mouse over.

**Comment by dcgrigsby** [comment]
the symmetry of the buttons is part of the design.  what stops you from being able to do this?

**Comment by sassinator** [comment]
@dcgrigsby these should match now. please take a look.
